export const positveComments = [

  ["Great service, thank you!",
    "Your products are amazing!",
    "I love your brand!",
    "Can't wait to see what's new!",
    "Please restock this item!",
    "Your customer support is fantastic!",
    "Best brand ever! ❤️",
    "Quick delivery, very impressed!",
    "Any upcoming sales or promotions?",
    "Keep up the good work!"]
  ,
  ["¡Excelente servicio, gracias!",
    "¡Tus productos son increíbles!",
    "¡Amo tu marca!",
    "¡No puedo esperar para ver las novedades!",
    "¡Por favor, repongan este producto!",
    "¡Su atención al cliente es fantástica!",
    "¡La mejor marca de todas! ❤️",
    "¡Entrega rápida, muy impresionado!",
    "¿Habrá próximas rebajas o promociones?",
    "¡Sigan con el buen trabajo!"]
  ,
  ["Excellent service, merci !",
    "Vos produits sont incroyables !",
    "J'adore votre marque !",
    "Hâte de voir les nouveautés !",
    "S'il vous plaît, réapprovisionnez cet article !",
    "Votre service client est fantastique !",
    "La meilleure marque de tous les temps ! ❤️",
    "Livraison rapide, très impressionné !",
    "Y aura-t-il des soldes ou des promotions à venir ?",
    "Continuez le bon travail !"]
  ,
  ["Hervorragender Service, danke!",
    "Eure Produkte sind unglaublich!",
    "Ich liebe eure Marke!",
    "Ich kann es kaum erwarten, was Neues kommt!",
    "Bitte füllt dieses Produkt wieder auf!",
    "Euer Kundenservice ist fantastisch!",
    "Beste Marke aller Zeiten! ❤️",
    "Schnelle Lieferung, sehr beeindruckt!",
    "Gibt es demnächst Sonderangebote oder Aktionen?",
    "Macht weiter so gute Arbeit!"]
  ,
  ["非常棒的服务，谢谢！",
    "你们的产品太棒了！",
    "我爱你们的品牌！",
    "迫不及待想看看新产品！",
    "请尽快补货这个商品！",
    "你们的客户服务太棒了！",
    "最棒的品牌！❤️",
    "发货很快，印象深刻！",
    "即将有特价或促销活动吗？",
    "继续保持好工作！"]

]