// https://en.wikipedia.org/wiki/List_of_ISO_639-1_codes
export const testData = [
  {
    "iso-639-1": "en",
    "langCode": "en",
    "language": "English",
    "phrases": [
      "Hello",
      "Goodbye",
      "Thank you",
      "Please",
      "Excuse me",
      "I'm sorry",
      "Yes",
      "No",
      "How are you?",
      "What is your name?",
      "Great service, thank you!",
    "Your products are amazing!",
    "I love your brand!",
    "Can't wait to see what's new!",
    "Please restock this item!",
    "Your customer support is fantastic!",
    "Best brand ever! ❤️",
    "Quick delivery, very impressed!",
    "Any upcoming sales or promotions?",
    "Keep up the good work!",
    "Terrible customer service, never buying from you again!",
    "Your products are low quality and overpriced.",
    "Disappointed with my purchase, it broke after a week.",
    "I've been waiting for my order for weeks, where is it?",
    "Your website is so hard to navigate, I can't find what I need.",
    "Stop sending me spam emails, it's annoying!",
    "Worst shopping experience ever, zero stars if I could.",
    "I can't believe I wasted my money on your products.",
    "Your company doesn't care about its customers.",
    "This is false advertising, the product doesn't do what was claimed."
    ]
  },
  {
    "iso-639-1": "es",
    "langCode": "es",
    "language": "Spanish",
    "phrases": [
      "Hola",
      "Adiós",
      "Gracias",
      "Por favor",
      "Perdón",
      "Lo siento",
      "Sí",
      "No",
      "¿Cómo estás?",
      "¿Cuál es tu nombre?",
      "¡Excelente servicio, gracias!",
    "¡Tus productos son increíbles!",
    "¡Amo tu marca!",
    "¡No puedo esperar para ver las novedades!",
    "¡Por favor, repongan este producto!",
    "¡Su atención al cliente es fantástica!",
    "¡La mejor marca de todas! ❤️",
    "¡Entrega rápida, muy impresionado!",
    "¿Habrá próximas rebajas o promociones?",
    "¡Sigan con el buen trabajo!",
    "Pésimo servicio al cliente, nunca más compro aquí.",
    "Sus productos son de mala calidad y caros.",
    "Decepcionado con mi compra, se rompió después de una semana.",
    "Llevo semanas esperando mi pedido, ¿dónde está?",
    "Su sitio web es difícil de navegar, no encuentro lo que necesito.",
    "Dejen de enviarme correos electrónicos no deseados, ¡es molesto!",
    "La peor experiencia de compra, cero estrellas si pudiera.",
    "No puedo creer que haya desperdiciado mi dinero en sus productos.",
    "Su empresa no se preocupa por sus clientes.",
    "Esto es publicidad engañosa, el producto no hace lo que se afirmaba."
    ]
  },
  {
    "iso-639-1": "fr",
    "langCode": "fr",
    "language": "French",
    "phrases": [
      "Bonjour",
      "Au revoir",
      "Merci",
      "S'il vous plaît",
      "Excusez-moi",
      "Je suis désolé(e)",
      "Oui",
      "Non",
      "Comment ça va?",
      "Comment tu t'appelles?",
      "Excellent service, merci !",
    "Vos produits sont incroyables !",
    "J'adore votre marque !",
    "Hâte de voir les nouveautés !",
    "S'il vous plaît, réapprovisionnez cet article !",
    "Votre service client est fantastique !",
    "La meilleure marque de tous les temps ! ❤️",
    "Livraison rapide, très impressionné !",
    "Y aura-t-il des soldes ou des promotions à venir ?",
    "Continuez le bon travail !",
    "Service client déplorable, je n'achèterai plus jamais chez vous !",
    "Vos produits sont de piètre qualité et trop chers.",
    "Déçu de mon achat, il s'est cassé au bout d'une semaine.",
    "J'attends ma commande depuis des semaines, où est-elle ?",
    "Votre site web est trop compliqué, je ne trouve pas ce dont j'ai besoin.",
    "Arrêtez de m'envoyer des emails indésirables, c'est agaçant !",
    "La pire expérience d'achat de ma vie, zéro étoile si je le pouvais.",
    "Je n'arrive pas à croire que j'aie gaspillé mon argent sur vos produits.",
    "Votre entreprise ne se soucie pas de ses clients.",
    "C'est de la publicité mensongère, le produit ne fait pas ce qui était prétendu."
    ]
  },
  {
    "iso-639-1": "de",
    "langCode": "de",
    "language": "German",
    "phrases": [
      "Hallo",
      "Auf Wiedersehen",
      "Danke",
      "Bitte",
      "Entschuldigung",
      "Es tut mir leid",
      "Ja",
      "Nein",
      "Wie geht es Ihnen?",
      "Wie ist Ihr Name?",
      "Hervorragender Service, danke!",
    "Eure Produkte sind unglaublich!",
    "Ich liebe eure Marke!",
    "Ich kann es kaum erwarten, was Neues kommt!",
    "Bitte füllt dieses Produkt wieder auf!",
    "Euer Kundenservice ist fantastisch!",
    "Beste Marke aller Zeiten! ❤️",
    "Schnelle Lieferung, sehr beeindruckt!",
    "Gibt es demnächst Sonderangebote oder Aktionen?",
    "Macht weiter so gute Arbeit!",
    "Schrecklicher Kundenservice, ich kaufe nie wieder bei euch!",
    "Eure Produkte sind von minderwertiger Qualität und überteuert.",
    "Enttäuscht von meinem Kauf, es ist nach einer Woche kaputt gegangen.",
    "Ich warte seit Wochen auf meine Bestellung, wo bleibt sie?",
    "Eure Webseite ist so schwer zu navigieren, ich finde nicht, was ich brauche.",
    "Hört auf, mir Spam-E-Mails zu schicken, es ist nervig!",
    "Schlechteste Einkaufserfahrung überhaupt, null Sterne, wenn ich könnte.",
    "Ich kann nicht glauben, dass ich mein Geld für eure Produkte verschwendet habe.",
    "Euer Unternehmen kümmert sich nicht um seine Kunden.",
    "Das ist irreführende Werbung, das Produkt hält nicht, was versprochen wurde."
    ]
  },
  {
    "iso-639-1": "zh",
    "langCode": "zh",
    "language": "Chinese",
    "phrases": [
      "你好",
      "再见",
      "谢谢",
      "请",
      "对不起",
      "对不起",
      "是的",
      "不是",
      "你好吗？",
      "你叫什么名字",
      "非常棒的服务，谢谢！",
    "你们的产品太棒了！",
    "我爱你们的品牌！",
    "迫不及待想看看新产品！",
    "请尽快补货这个商品！",
    "你们的客户服务太棒了！",
    "最棒的品牌！❤️",
    "发货很快，印象深刻！",
    "即将有特价或促销活动吗？",
    "继续保持好工作！",
    "糟糕的客户服务，再也不会在你们这里购买了！",
    "你们的产品质量太差，而且价格也太高。",
    "对我的购买感到失望，一周后就坏了。",
    "我已经等了好几周了，我的订单在哪？",
    "你们的网站太难用了，我找不到我需要的东西。",
    "别再发垃圾邮件给我，太烦人了！",
    "有史以来最糟糕的购物体验，如果能给零星的话我会的。",
    "我简直不敢相信我竟然在你们的产品上浪费了我的钱。",
    "你们公司根本不在乎客户。",
    "这是虚假广告，产品根本做不到广告上宣称的效果。"
    ]
  },
  {
    "iso-639-1": "ja",
    "langCode": "ja",
    "language": "Japanese",
    "phrases": [
      "こんにちは",
      "さようなら",
      "ありがとう",
      "お願いします",
      "すみません",
      "ごめんなさい",
      "はい",
      "いいえ",
      "お元気ですか？",
      "お名前は何ですか？",
      "素晴らしいサービス、ありがとう！",
      "あなたの製品は素晴らしいです！",
      "あなたのブランドが大好きです！",
      "新商品を楽しみにしています！",
      "このアイテムを再入荷してください！",
      "お客様サポートは素晴らしいです！",
      "最高のブランド！ ❤️",
      "迅速な配達、非常に感銘を受けました！",
      "今後のセールやプロモーションはありますか？",
      "お仕事、がんばってください！",
      "最悪のカスタマーサービス、二度と買いません！",
      "製品は低品質で高すぎます。",
      "購入に失望しました、1週間後に壊れました。",
      "注文が数週間待っています、どこですか？",
      "ウェブサイトがナビゲーションしにくい、必要なものが見つかりません。",
      "スパムメールの送信をやめてください、迷惑です！",
      "最悪のショッピング体験、星0つです。"
    ]
  },
  {
    "iso-639-1": "ar",
    "langCode": "ar",
    "language": "Arabic",
    "phrases": [
      "مرحبًا",
      "وداعًا",
      "شكرًا",
      "من فضلك",
      "عفوًا",
      "آسف",
      "نعم",
      "لا",
      "كيف حالك؟",
      "ما اسمك؟",
      "خدمة رائعة، شكرًا!",
      "منتجاتك رائعة!",
      "أنا أحب علامتك التجارية!",
      "لا يمكن الانتظار لرؤية ما هو جديد!",
      "من فضلك، قم بإعادة توفير هذا العنصر!",
      "دعم العملاء لديك رائع!",
      "أفضل علامة تجارية على الإطلاق! ❤️",
      "توصيل سريع، أنبهرت كثيرًا!",
      "هل هناك تخفيضات أو عروض قادمة؟",
      "استمر في العمل الجيد!",
      "خدمة العملاء سيئة جدًا، لن أشتري مرة أخرى!",
      "منتجاتك جودتها منخفضة ومبالغ في سعرها.",
      "أنا مخيب من شرائي، انكسرت بعد أسبوع.",
      "لقد انتظرت طلبي لأسابيع، أين هو؟",
      "موقع الويب صعب للتنقل، لا يمكنني العثور على ما أحتاجه.",
      "توقف عن إرسال رسائل البريد العشوائي، إنه مزعج!",
      "أسوأ تجربة تسوق على الإطلاق، صفر نجوم إذا كنت قادرًا."
    ]
  },
  {
    "iso-639-1": "ru",
    "langCode": "ru",
    "language": "Russian",
    "phrases": [
      "Привет",
    "До свидания",
    "Спасибо",
    "Пожалуйста",
    "Извините",
    "Простите",
    "Да",
    "Нет",
    "Как вы?",
    "Как вас зовут?",
    "Отличный сервис, спасибо!",
    "Ваши продукты удивительны!",
    "Я люблю ваш бренд!",
    "Не могу дождаться новинок!",
    "Пожалуйста, верните этот товар в наличие!",
    "Ваша поддержка клиентов фантастическая!",
    "Лучший бренд в истории! ❤️",
    "Быстрая доставка, впечатлен!",
    "Будут ли какие-либо предстоящие распродажи или акции?",
    "Продолжайте в том же духе!",
    "Ужасное обслуживание, больше никогда не буду у вас покупать!",
    "Ваши продукты низкого качества и переоценены.",
    "Разочарован своей покупкой, сломалось через неделю.",
    "Я жду свой заказ недели, где он?",
    "Ваш сайт так трудно навигировать, я не могу найти, что мне нужно.",
    "Прекратите отправлять мне спам по электронной почте, это раздражает!",
    "Худший опыт покупок, ноль звезд, если бы я мог."
    ]
  },
  {
    "iso-639-1": "it",
    "langCode": "it",
    "language": "Italian",
    "phrases": [
      "Ciao",
    "Arrivederci",
    "Grazie",
    "Per favore",
    "Mi scusi",
    "Mi dispiace",
    "Sì",
    "No",
    "Come stai?",
    "Come ti chiami?",
    "Ottimo servizio, grazie!",
    "I tuoi prodotti sono incredibili!",
    "Amo il tuo marchio!",
    "Non vedo l'ora di vedere le novità!",
    "Per favore, rimettete in stock questo articolo!",
    "Il vostro supporto clienti è fantastico!",
    "Miglior marchio di sempre! ❤️",
    "Consegna veloce, molto impressionato!",
    "Ci saranno future vendite o promozioni?",
    "Continuate così!",
    "Pessimo servizio clienti, non comprerò mai più da voi!",
    "I vostri prodotti sono di bassa qualità e troppo cari.",
    "Sono deluso dal mio acquisto, si è rotto dopo una settimana.",
    "Aspetto il mio ordine da settimane, dov'è?",
    "Il vostro sito web è così difficile da navigare, non riesco a trovare ciò che mi serve.",
    "Smettete di inviarmi email indesiderate, è fastidioso!",
    "Peggiore esperienza di acquisto di sempre, zero stelle se potessi."
    ]
  },
  {
    "iso-639-1": "nl",
    "langCode": "nl",
    "language": "Dutch",
    "phrases": [
      "Hallo",
    "Tot ziens",
    "Dank je",
    "Alsjeblieft",
    "Excuseer me",
    "Het spijt me",
    "Ja",
    "Nee",
    "Hoe gaat het met je?",
    "Wat is je naam?",
    "Geweldige service, bedankt!",
    "Jouw producten zijn geweldig!",
    "Ik hou van jouw merk!",
    "Kan niet wachten om te zien wat er nieuw is!",
    "Vul dit item alsjeblieft aan!",
    "Jouw klantenservice is fantastisch!",
    "Beste merk ooit! ❤️",
    "Snelle levering, zeer onder de indruk!",
    "Nog komende sales of promoties?",
    "Ga zo door met het goede werk!",
    "Vreselijke klantenservice, koop hier nooit meer!",
    "Jouw producten zijn van lage kwaliteit en te duur.",
    "Teleurgesteld in mijn aankoop, het brak na een week.",
    "Ik wacht al weken op mijn bestelling, waar is het?",
    "Jouw website is zo moeilijk te navigeren, ik kan niet vinden wat ik nodig heb.",
    "Stop met het sturen van spammails, het is irritant!",
    "Slechtste winkelervaring ooit, nul sterren als dat kon."
    ]
  },
  {
    "iso-639-1": "pt",
    "langCode": "pt",
    "language": "Portuguese",
    "phrases": [
      "Olá",
    "Adeus",
    "Obrigado",
    "Por favor",
    "Com licença",
    "Desculpe-me",
    "Sim",
    "Não",
    "Como você está?",
    "Qual é o seu nome?",
    "Ótimo serviço, obrigado!",
    "Seus produtos são incríveis!",
    "Eu amo sua marca!",
    "Mal posso esperar para ver o que há de novo!",
    "Por favor, reponha este item!",
    "Seu suporte ao cliente é fantástico!",
    "Melhor marca de sempre! ❤️",
    "Entrega rápida, muito impressionado!",
    "Haverá alguma venda ou promoção em breve?",
    "Continue com o bom trabalho!",
    "Atendimento ao cliente terrível, nunca mais compro de vocês!",
    "Seus produtos são de baixa qualidade e caros demais.",
    "Decepcionado com minha compra, quebrou após uma semana.",
    "Estou esperando meu pedido há semanas, onde está?",
    "Seu site é tão difícil de navegar, não consigo encontrar o que preciso.",
    "Pare de me enviar emails de spam, é irritante!",
    "Pior experiência de compras de sempre, zero estrelas se pudesse."
    ]
  },
  {
    "iso-639-1": "ko",
    "langCode": "ko",
    "language": "Korean",
    "phrases": [
      "안녕하세요",
    "안녕히 가세요",
    "감사합니다",
    "부탁합니다",
    "죄송합니다",
    "미안합니다",
    "예",
    "아니요",
    "어떻게 지내세요?",
    "당신의 이름은 뭐에요?",
    "좋은 서비스, 감사합니다!",
    "귀하의 제품은 놀라운 것입니다!",
    "당신의 브랜드를 사랑합니다!",
    "새 제품이 나오는 걸 기대할 수 없어요!",
    "이 상품을 재입고해 주세요!",
    "귀하의 고객 지원은 환상적입니다!",
    "최고의 브랜드 ever! ❤️",
    "빠른 배송, 매우 감동받았어요!",
    "다가오는 세일이나 프로모션이 있을까요?",
    "계속 좋은 일 하세요!",
    "형편없는 고객 서비스, 이젠 여기서 사지 않아요!",
    "귀하의 제품은 저급하고 가격이 비싸요.",
    "구매에 실망했어요, 일주일 뒤에 고장났어요.",
    "주문한 지 몇 주가 지났어, 어디에요?",
    "귀하의 웹사이트 네비게이션 너무 어려워, 필요한 걸 찾을 수가 없어요.",
    "스팸 이메일 보내지 마세요, 짜증나요!",
    "지금까지 겪어본 최악의 쇼핑 경험, 별 0개 주고 싶어요."
    ]
  },
  {
    "iso-639-1": "tr",
    "langCode": "tr",
    "language": "Turkish",
    "phrases": [
      "Merhaba",
    "Hoşça kal",
    "Teşekkür ederim",
    "Lütfen",
    "Affedersiniz",
    "Özür dilerim",
    "Evet",
    "Hayır",
    "Nasılsınız?",
    "Adınız ne?",
    "Harika hizmet, teşekkür ederim!",
    "Ürünleriniz harika!",
    "Markanızı seviyorum!",
    "Yeni ürünleri görmek için sabırsızlanıyorum!",
    "Lütfen bu ürünü tekrar stoklayın!",
    "Müşteri desteğiniz harika!",
    "En iyi marka! ❤️",
    "Hızlı teslimat, çok etkilendim!",
    "Yaklaşan indirimler veya promosyonlar var mı?",
    "İyi işlere devam edin!",
    "Korkunç müşteri hizmetleri, bir daha asla buradan alışveriş yapmam!",
    "Ürünleriniz düşük kalitede ve çok pahalı.",
    "Alışverişimden hayal kırıklığına uğradım, bir hafta sonra kırıldı.",
    "Siparişimi haftalar önce bekliyorum, nerede?",
    "Web siteniz çok zor geziniliyor, ihtiyacım olanı bulamıyorum.",
    "Bana spam e-posta göndermeyi bırakın, rahatsız edici!",
    "Şimdiye kadar yaşadığım en kötü alışveriş deneyimi, eğer mümkünse sıfır yıldız verirdim."
    ]
  },
  {
    "iso-639-1": "sv",
    "langCode": "sv",
    "language": "Swedish",
    "phrases": [
      "Hej",
    "Adjö",
    "Tack",
    "Snälla",
    "Ursäkta mig",
    "Förlåt",
    "Ja",
    "Nej",
    "Hur mår du?",
    "Vad heter du?",
    "Fantastisk service, tack!",
    "Dina produkter är fantastiska!",
    "Jag älskar ditt varumärke!",
    "Längtar efter att se vad som är nytt!",
    "Fyll på den här produkten, snälla!",
    "Ditt kundstöd är fantastiskt!",
    "Bästa varumärket någonsin! ❤️",
    "Snabb leverans, mycket imponerad!",
    "Några kommande reor eller kampanjer?",
    "Fortsätt det bra arbetet!",
    "Uselt kundstöd, köper aldrig härifrån igen!",
    "Dina produkter är låg kvalitet och överprissatta.",
    "Besviken över mitt köp, det gick sönder efter en vecka.",
    "Jag har väntat på min order i veckor, var är den?",
    "Er webbplats är så svår att navigera, jag hittar inte vad jag behöver.",
    "Sluta skicka mig spam-mail, det är irriterande!",
    "Sämsta shoppingupplevelsen någonsin, noll stjärnor om jag kunde."
    ]
  },
  {
    "iso-639-1": "el",
    "langCode": "el",
    "language": "Greek",
    "phrases": [
      "Γειά σας",
      "Αντίο",
      "Ευχαριστώ",
      "Παρακαλώ",
      "Συγνώμη",
      "Λυπάμαι",
      "Ναι",
      "Όχι",
      "Πώς είστε;",
      "Πώς σας λένε;",
      "Εξαιρετική εξυπηρέτηση, ευχαριστώ!",
      "Τα προϊόντα σας είναι εκπληκτικά!",
      "Λατρεύω το σήμα σας!",
      "Ανυπομονώ να δω τι νέο υπάρχει!",
      "Παρακαλώ, επαναστατείτε αυτό το αντικείμενο!",
      "Η υποστήριξη πελατών σας είναι φανταστική!",
      "Καλύτερη μάρκα ποτέ! ❤️",
      "Γρήγορη παράδοση, εντυπωσιάστηκα πολύ!",
      "Υπάρχουν επερχόμενες εκπτώσεις ή προσφορές;",
      "Συνεχίστε το καλό έργο!",
      "Απαίσια εξυπηρέτηση πελατών, δεν θα ξανααγοράσω από εσάς!",
      "Τα προϊόντα σας είναι χαμηλής ποιότητας και υπερτιμημένα.",
      "Απογοητευμένος με την αγορά μου, σπάσανε μετά από μια εβδομάδα.",
      "Περιμένω την παραγγελία μου εδώ και εβδομάδες, πού είναι;",
      "Ο ιστότοπός σας είναι τόσο δύσκολος στην πλοήγηση, δεν μπορώ να βρω αυτό που χρειάζομαι.",
      "Σταματήστε να μου στέλνετε ανεπιθύμητα emails, είναι ενοχλητικά!",
      "Η χειρότερη εμπειρία αγορών που είχα ποτέ, μηδέν αστέρια αν μπορούσα."
    ]
  },
  {
    "iso-639-1": "he",
    "langCode": "he",
    "language": "Hebrew",
    "phrases": [
      "שלום (Shalom)",
      "להתראות (Lehitra'ot)",
      "תודה (Toda)",
      "בבקשה (Bevakasha)",
      "סליחה (Slicha)",
      "מצטער (Mitsta'er)",
      "כן (Ken)",
      "לא (Lo)",
      "איך אתה? (Eich atah?)",
      "מה שמך? (Ma shmecha?)"
    ]
  },
  {
    "iso-639-1": "hi",
    "langCode": "hi",
    "language": "Hindi",
    "phrases": [
      "नमस्ते",
    "ख़ुदा हाफ़िज़",
    "धन्यवाद",
    "कृपया",
    "मुझे माफ़ कीजिए",
    "मुझे खेद है",
    "हाँ",
    "नहीं",
    "आप कैसे हैं?",
    "आपका नाम क्या है?",
    "बढ़िया सेवा, धन्यवाद!",
    "आपके उत्पाद शानदार हैं!",
    "मुझे आपका ब्रांड पसंद है!",
    "मैं इसके नए क्या है देखने के लिए उत्सुक हूँ!",
    "कृपया इस आइटम को पुनः स्टॉक में डालें!",
    "आपका ग्राहक समर्थन बहुत शानदार है!",
    "सबसे बेहतर ब्रांड कभी! ❤️",
    "तेज़ वितरण, बहुत प्रभावित हुआ!",
    "कोई आने वाले छूट या प्रमोशन?",
    "अच्छे काम में जारी रखें!",
    "बेहद ख़राब ग्राहक सेवा, कभी भी आपसे नहीं खरीदूंगा!",
    "आपके उत्पाद नीची गुणवत्ता और अत्यधिक महंगे हैं।",
    "मेरी खरीद पर निराश हूँ, एक हफ्ते बाद टूट गया।",
    "मैंने अपनी आदेश का इंतजार हफ्तों से किया है, वहाँ कहाँ है?",
    "आपकी वेबसाइट इतनी पेचीदा है कि मैं नहीं पा सकता जो मुझे चाहिए।",
    "मुझे स्पैम ईमेल भेजना बंद करें, यह ज़हरीला है!",
    "सबसे ख़राब ख़रीददारी अनुभव कभी, नीचे ज़रा से भी तारा देता।"
    ]
  },
  {
    "iso-639-1": "th",
    "langCode": "th",
    "language": "Thai",
    "phrases": [
      "สวัสดี (Sawasdee)",
      "ลาก่อน (La khon)",
      "ขอบคุณ (Khop khun)",
      "โปรด (Prôd)",
      "ขอโทษ (Kho thot)",
      "โทษ (Thot)",
      "ใช่ (Chai)",
      "ไม่ (Mai)",
      "ท่านเป็นอย่างไร? (Thān pen yā̀ng rai?)",
      "คุณชื่ออะไร? (Khun chêu a rai?)"
    ]
  },
  {
    "iso-639-1": "pl",
    "langCode": "pl",
    "language": "Polish",
    "phrases": [
      "Cześć",
    "Do widzenia",
    "Dziękuję",
    "Proszę",
    "Przepraszam",
    "Przepraszam",
    "Tak",
    "Nie",
    "Jak się masz?",
    "Jak masz na imię?",
    "Świetna obsługa, dziękuję!",
    "Twoje produkty są niesamowite!",
    "Uwielbiam twoją markę!",
    "Nie mogę się doczekać nowości!",
    "Proszę uzupełnić ten produkt!",
    "Twoje wsparcie dla klienta jest fantastyczne!",
    "Najlepsza marka wszech czasów! ❤️",
    "Szybka dostawa, bardzo pod wrażeniem!",
    "Czy będą jakieś nadchodzące wyprzedaże lub promocje?",
    "Tak trzymaj!",
    "Fatalna obsługa klienta, nigdy więcej nie kupię od was!",
    "Wasze produkty są niskiej jakości i zbyt drogie.",
    "Rozczarowany swoim zakupem, zepsuło się po tygodniu.",
    "Czekam na moje zamówienie od tygodni, gdzie jest?",
    "Wasza strona internetowa jest tak trudna do nawigacji, nie mogę znaleźć tego, czego potrzebuję.",
    "Przestańcie wysyłać mi spam, to irytujące!",
    "Najgorsze doświadczenie zakupowe, zero gwiazdek, gdyby się dało."
    ]
  },
  {
    "iso-639-1": "vi",
    "langCode": "vi",
    "language": "Vietnamese",
    "phrases": [
      "Xin chào",
      "Tạm biệt",
      "Cảm ơn",
      "Làm ơn",
      "Xin lỗi",
      "Tôi xin lỗi",
      "Vâng",
      "Không",
      "Bạn khỏe không?",
      "Tên bạn là gì?"
    ]
  }
  // Add more languages and phrases as needed
]
